[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "package.json,package-lock.json,env.example"
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_VERSION"

[[redirects]]
  from = "/api/*"
  to = "https://ai-molecular-research.doctorcorelabs.workers.dev/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


[[redirects]]
  # SPA fallback: send all non-file routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
