name = "ai-molecular-research"
main = "workers/index.ts"
compatibility_date = "2023-12-01"

[vars]
# Environment variables will be loaded from .dev.vars for local development
# For production, set these via Cloudflare dashboard or wrangler secret commands
# Removed TURNSTILE_SECRET_KEY; no longer required

[env.production]
name = "ai-molecular-research"

# Workers.dev deployments do not need routes; remove invalid pattern

# Ensure env-specific vars/ai blocks exist (not inherited from top-level)
[env.production.vars]

[env.production.ai]
binding = "AI"

# AI binding for Cloudflare AI
[ai]
binding = "AI"
